apiVersion: v1
kind: Service
metadata:
  name: currency-conversion-api
spec:
  type: NodePort
  selector:
    app: currency-conversion-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000  # Optional: specify a port or let Kubernetes assign one

